name: Custom Notifications
on:
  schedule:
    - cron: '30 17 * * 6' # 5:30 pm UTC every saturday
  issues:
    types: [opened, edited, deleted, closed]
  issue_comment:
    types: [created]
  workflow_run:
    workflows: ["Release"]
    types: [completed]
  pull_request_target:
    types: [opened, closed, edited, review_requested]

jobs:
  issue-comment-notification:
    if: github.event_name == 'issues' || github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Issue or Comment
        if: github.actor != 'sujaynsv'
        run: |
          curl -H "Content-Type: application/json" -X POST \
          "${{ secrets.DISCORD_WEBHOOK }}" \
          -d "{\"content\": \"*New issue/comment from **${{ github.actor }}***\n${{ github.event.issue.html_url }}\"}"

  build-status-notification:
    if: github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Build Status
        run: |
          curl -H "Content-Type: application/json" -X POST \
          "${{ secrets.DISCORD_WEBHOOK }}" \
          -d "{\"content\": \"*Workflow run for **${{ github.repository }}***\n${{ github.event.workflow_run.name }} - ${{ github.event.workflow_run.conclusion }}\"}"

  pull-request-notification:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: Notify on PR related activities
        if: github.actor != 'sujaynsv'
        run: |
          curl -H "Content-Type: application/json" -X POST \
          "${{ secrets.DISCORD_WEBHOOK }}" \
          -d "{\"content\": \"*New PR activity from **${{ github.actor }}***\n${{ github.event.pull_request.html_url }}\"}"